etcd:
  url: http://localhost:2479
services:
  monitorManagementUrl: http://localhost:8089
server:
  port: 8084
logging:
  level:
    com.rackspace.salus.zone_watcher: debug
    com.rackspace.salus.telemetry.etcd: debug