spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: salus-telemetry-zone-watcher
management:
  metrics:
    export:
      influx:
        uri: ${salus.metrics.influx.uri:http://localhost:8086}
        db: salus
        enabled: ${salus.metrics.influx.enabled:false}